name: keep-app-awake

on:
  schedule:
    - cron: "0 */3 * * *"   # Ejecuta cada 6 horas
  workflow_dispatch:        # Permite lanzarlo manualmente si quieres probar

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: curl -s -o /dev/null -w "%{http_code}" https://statistical-tool-mp.streamlit.app/
