name: keep-app-awake

on:
  schedule:
    - cron: "0 */3 * * *"   # Ejecuta cada 3 horas
  workflow_dispatch:        # Permite lanzarlo manualmente para probar

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Warm up Streamlit app (retry until awake)
        run: |
          URL="https://statistical-tool-mp.streamlit.app/?nocache=$(date +%s)"
          for i in {1..6}; do
            echo "Ping #$i"
            CONTENT=$(curl -s -H "User-Agent: Mozilla/5.0" -H "Cache-Control: no-cache" "$URL")
            if echo "$CONTENT" | grep -qi "Zzz"; then
              echo "Aún está dormida. Esperando 20s y reintentando..."
              sleep 20
            else
              echo "¡App despierta!"
              exit 0
            fi
          done
          echo "Sigue dormida tras varios intentos."
          exit 1
